name: rivership_workspace
description: Infrastructure used by whynotmake.it for maximum velocity
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.10.0"
  
dev_dependencies:
  lintervention: ^0.3.1
  melos: ^6.3.2
