name: Bug Report
description: Create a report to help us improve
title: "fix: "
labels: ["bug"]
body:
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package is this bug report for?
      options:
        - heroine
        - motor
        - rivership
        - rivership_test
        - scroll_drag_detector
        - snaptest
        - springster
        - stupid_simple_sheet
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false 