name: Documentation
description: Improve the documentation so all collaborators have a common understanding
title: "docs: "
labels: ["documentation"]
body:
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package's documentation needs to be improved?
      options:
        - heroine
        - motor
        - rivership
        - rivership_test
        - scroll_drag_detector
        - snaptest
        - springster
        - stupid_simple_sheet
        - all
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clearly describe what documentation you are looking to add or improve.
    validations:
      required: true
