name: Feature Request
description: A new feature to be added to the project
title: "feat: "
labels: ["feature"]
body:
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package is this feature request for?
      options:
        - rivership
        - heroine
        - springster
        - rivership_test
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clearly describe what you are looking to add. The more context the better.
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: List the requirements that need to be fulfilled
      placeholder: |
        - [ ] Requirement 1
        - [ ] Requirement 2
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false 