name: Style Changes
description: Changes that do not affect the meaning of the code (white space, formatting, missing semi-colons, etc)
title: "style: "
labels: ["style"]
body:
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package needs style changes?
      options:
        - rivership
        - heroine
        - springster
        - rivership_test
        - all
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clearly describe what you are looking to change and why.
      placeholder: |
        - Files/areas that need style changes
        - Specific style issues to address
        - Motivation for the changes
    validations:
      required: true

  - type: checkboxes
    id: style_type
    attributes:
      label: Type of Style Changes
      description: What kind of style changes are needed?
      options:
        - label: Formatting (whitespace, indentation)
        - label: Code organization
        - label: Naming conventions
        - label: Other (specify in description)

  - type: checkboxes
    id: requirements
    attributes:
      label: Requirements
      description: Make sure the following requirements are met
      options:
        - label: Changes are consistent with project style guide
          required: true 