name: Test
description: Adding missing tests or correcting existing tests
title: "test: "
labels: ["test"]
body:
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package needs test changes?
      options:
        - heroine
        - motor
        - rivership
        - rivership_test
        - scroll_drag_detector
        - snaptest
        - springster
        - stupid_simple_sheet
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: List out the tests that need to be added or changed. Please also include any information as to why this was not covered in the past.
    validations:
      required: true
