name: motor_example
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1
resolution: workspace

environment:
  sdk: ^3.10.0
  flutter: ^3.27.0

dependencies:
  auto_route: ^10.0.1
  example_design:
    path: ../../example_design
  flutter:
    sdk: flutter
  motor:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Archivo
      fonts:
        - asset: lib/assets/Archivo-VariableFont_wdth,wght.ttf
